name: Docker Image CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Build the Docker image
        run: |
          docker build -t shakir737/next-js .
          docker login -u shakir737 -p Anilla621#
          docker push  shakir737/next-js:latest
