name: Docker Image CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Build the Docker image
        run1: docker build -t shakir737/next-js .
        run2: docker login -u shakir737 -p Anilla621#
        run3: docker push  shakir737/next-js:latest
